version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - u2241890_auth
    volumes:
      - ./:/var/www/mandomemori/
    ports:
      - "5000:80"
  u2241890_auth:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mandomemori2022
      MYSQL_DATABASE: u2241890_auth
      MYSQL_USER: u2241890_MandoBD
      MYSQL_PASSWORD: mandomemori2022
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - u2241890_auth
    environment:
      PMA_HOST: u2241890_auth
    restart: always
    ports:
      - "5001:80"